// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzXNqgwRlaKYOKGDRfLKxA0WHApQ-V2Y',
    appId: '1:170584725436:web:428e16c0c29166e7443db9',
    messagingSenderId: '170584725436',
    projectId: 'medi-pharma-rafat',
    authDomain: 'medi-pharma-rafat.firebaseapp.com',
    storageBucket: 'medi-pharma-rafat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9BSBYuOujnGczIDf-sfOOshzDiRld90',
    appId: '1:170584725436:android:3a76078da5b83ad0443db9',
    messagingSenderId: '170584725436',
    projectId: 'medi-pharma-rafat',
    storageBucket: 'medi-pharma-rafat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3aq4KPO5CYZcvESRY9nNMvGVwzVE8SE',
    appId: '1:170584725436:ios:fc1635cfd29ca11b443db9',
    messagingSenderId: '170584725436',
    projectId: 'medi-pharma-rafat',
    storageBucket: 'medi-pharma-rafat.firebasestorage.app',
    iosBundleId: 'com.example.mediPharma',
  );
}
